/**
 * @file ITacticalUI.h
 * @brief Tactical-layer UI boundary for redraws, tactical dialogs, and winner notifications.
 *
 * @author Tom Stephens, gpt-5.3-codex (medium)
 * @date Created: Mar 29, 2026
 * @date Last Modified: Mar 29, 2026
 */

#ifndef _ITACTICALUI_H_
#define _ITACTICALUI_H_

#include <string>
#include <vector>

#include "ships/FVehicle.h"

namespace Frontier {

struct FTacticalCombatReportSummary;

/**
 * @brief Pure abstract interface used by tactical game logic to request UI actions.
 *
 * The tactical model emits user-facing events through this seam so model code
 * remains independent from wxWidgets UI types and runtime ownership.
 *
 * @author Tom Stephens, gpt-5.3-codex (medium)
 * @date Created: Mar 29, 2026
 * @date Last Modified: Mar 29, 2026
 */
class ITacticalUI {
public:
/**
 * @brief Virtual destructor for interface-safe polymorphic cleanup.
 *
 * @author Tom Stephens, gpt-5.3-codex (medium)
 * @date Created: Mar 29, 2026
 * @date Last Modified: Mar 29, 2026
 */
virtual ~ITacticalUI() {}

/**
 * @brief Request a tactical redraw from the UI layer.
 *
 * Called when tactical model state changes and rendered surfaces should refresh.
 *
 * @author Tom Stephens, gpt-5.3-codex (medium)
 * @date Created: Mar 29, 2026
 * @date Last Modified: Mar 29, 2026
 */
virtual void requestRedraw() = 0;

/**
 * @brief Show an informational tactical message.
 *
 * @param title Modal/dialog title text.
 * @param body Message body text.
 *
 * @author Tom Stephens, gpt-5.3-codex (medium)
 * @date Created: Mar 29, 2026
 * @date Last Modified: Mar 29, 2026
 */
virtual void showMessage(const std::string& title, const std::string& body) = 0;

/**
 * @brief Show the tactical damage summary dialog.
 *
 * @param summary Structured tactical summary generated by report aggregation.
 * @return int Modal/dialog return code, where 0 indicates success.
 *
 * @author Tom Stephens, gpt-5.3-codex (medium)
 * @date Created: Mar 29, 2026
 * @date Last Modified: Mar 29, 2026
 */
virtual int showDamageSummary(const FTacticalCombatReportSummary& summary) = 0;

/**
 * @brief Launch ICM targeting selection for intercept-capable defenders.
 *
 * @param icmData Mutable weapon/interceptor assignment candidates.
 * @param defenders Defending ships eligible to allocate ICM shots.
 * @return int Modal/dialog return code, where 0 indicates success.
 *
 * @author Tom Stephens, gpt-5.3-codex (medium)
 * @date Created: Mar 29, 2026
 * @date Last Modified: Mar 29, 2026
 */
virtual int runICMSelection(std::vector<ICMData*>& icmData, VehicleList* defenders) = 0;

/**
 * @brief Notify battle completion with the winning side identity.
 *
 * @param attackerWins True when the attacker side wins; false for defender win.
 *
 * @author Tom Stephens, gpt-5.3-codex (medium)
 * @date Created: Mar 29, 2026
 * @date Last Modified: Mar 29, 2026
 */
virtual void notifyWinner(bool attackerWins) = 0;
};

};

#endif //_ITACTICALUI_H_
